repos:
  - repo: local
    hooks:
    - id: black
      name: apply black
      language: system
      types: [python]
      entry: pipenv run black
    - id: ruff
      name: ruff
      language: system
      types: [python]
      entry: pipenv run ruff check
      args: [--fix]
