# Generated by Django 3.2.5 on 2021-07-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the bus stop')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_stop', to='travel.busstopdate')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.bus')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_stop', to='travel.busstopdate')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.driver')),
                ('intermediate_stops', models.ManyToManyField(blank=True, null=True, related_name='intermediate_stop', to='travel.BusStopDate')),
            ],
        ),
    ]
