# Generated by Django 3.2.5 on 2021-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstopdate',
            name='datetime',
        ),
        migrations.AddField(
            model_name='busstopdate',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='busstopdate',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
