# Generated by Django 3.2.5 on 2024-10-27 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0002_auto_20211109_1456'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endbusstop',
            options={'default_related_name': 'end_bus_stops'},
        ),
        migrations.AlterModelOptions(
            name='startbusstop',
            options={'default_related_name': 'start_bus_stops'},
        ),
        migrations.AlterField(
            model_name='endbusstop',
            name='place',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='end_bus_stops',
                to='geography.place',
            ),
        ),
        migrations.AlterField(
            model_name='endbusstop',
            name='start',
            field=models.OneToOneField(
                help_text='Starting BusStop that will form an itinerary',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='end_bus_stops',
                to='travel.startbusstop',
                verbose_name='Starting BusStop',
            ),
        ),
        migrations.AlterField(
            model_name='startbusstop',
            name='place',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='start_bus_stops',
                to='geography.place',
            ),
        ),
        migrations.AlterField(
            model_name='startbusstop',
            name='user',
            field=models.ForeignKey(
                help_text='User that booked a bus',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='start_bus_stops',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'bus',
                    models.ForeignKey(
                        help_text='Bus for this shift',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shifts',
                        to='fleet.bus',
                        verbose_name='Bus',
                    ),
                ),
                (
                    'driver',
                    models.ForeignKey(
                        help_text='Driver for this shift',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shifts',
                        to='fleet.driver',
                        verbose_name='Bus driver',
                    ),
                ),
            ],
            options={
                'default_related_name': 'shifts',
            },
        ),
        migrations.AddField(
            model_name='endbusstop',
            name='shift',
            field=models.ForeignKey(
                blank=True,
                help_text='Bus shift that will handle these stops',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='end_bus_stops',
                to='travel.busshift',
                verbose_name='Bus shift',
            ),
        ),
    ]
