# Generated by Django 3.2.5 on 2023-03-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_shift', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_shift', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_time', models.DateTimeField()),
                ('bus_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_stop', to='route.busshift')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stop', to='geography.place')),
            ],
        ),
    ]
