# Generated by Django 3.2.5 on 2022-06-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoptime', models.TimeField()),
                ('busshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.busshift')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
            options={
                'ordering': ['stoptime'],
            },
        ),
        migrations.AddField(
            model_name='busshift',
            name='stops',
            field=models.ManyToManyField(through='route.BusStop', to='geography.Place'),
        ),
    ]
