# Generated by Django 3.2.5 on 2021-08-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_rename_licence_place_bus_licence_plate'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.busstop')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
                ('stops', models.ManyToManyField(to='route.BusStopDate')),
            ],
        ),
    ]
