# Generated by Django 3.2.5 on 2022-06-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='bus_stop',
        ),
        migrations.AddField(
            model_name='busshift',
            name='end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='route.busstop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busshift',
            name='start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='route.busstop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busshift',
            name='steps',
            field=models.ManyToManyField(to='route.BusStop'),
        ),
    ]
