# Generated by Django 3.2.5 on 2022-06-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20220613_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='steps',
            field=models.ManyToManyField(blank=True, null=True, to='route.BusStop'),
        ),
    ]
