# Generated by Django 3.2.5 on 2022-06-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('route', '0003_alter_busshift_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='geography.place'),
        ),
    ]
