# Generated by Django 3.2.5 on 2022-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_alter_busstop_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='minutes',
        ),
        migrations.AddField(
            model_name='busstop',
            name='time',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busshift',
            name='steps',
            field=models.ManyToManyField(blank=True, to='route.BusStop'),
        ),
    ]
