# Generated by Django 3.2.5 on 2022-06-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('route', '0005_auto_20220615_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='fleet.bus'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='fleet.driver'),
        ),
    ]
