# Generated by Django 3.2.5 on 2022-07-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.driver')),
                ('stops', models.ManyToManyField(related_name='bus_shifts', to='routes.BusStop')),
            ],
        ),
    ]
