# Generated by Django 3.2.5 on 2024-06-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='start_time',
        ),
    ]
