# Generated by Django 3.2.5 on 2024-11-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.bus')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('stops', models.ManyToManyField(to='shifts.BusStop')),
            ],
        ),
    ]
