# Generated by Django 3.2.5 on 2024-11-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='time',
            new_name='date_time',
        ),
    ]
