# Generated by Django 3.2.5 on 2024-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('shifts', '0002_rename_time_busstop_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='bus',
        ),
        migrations.AddField(
            model_name='busshift',
            name='bus',
            field=models.ManyToManyField(to='fleet.Bus'),
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='driver',
        ),
        migrations.AddField(
            model_name='busshift',
            name='driver',
            field=models.ManyToManyField(to='fleet.Driver'),
        ),
    ]
