# Generated by Django 3.2.5 on 2024-11-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('shifts', '0003_auto_20241116_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='bus',
        ),
        migrations.AddField(
            model_name='busshift',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.bus'),
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='driver',
        ),
        migrations.AddField(
            model_name='busshift',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.driver'),
        ),
    ]
