# Generated by Django 3.2.5 on 2022-01-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fleet.bus')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('busshift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='busstops', to='busservice.busshift')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='geography.place')),
            ],
        ),
    ]
