# Generated by Django 3.2.5 on 2021-10-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        ("fleet", "0002_alter_driver_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Name of the bus stop"
                    ),
                ),
                (
                    "is_transfer_stop",
                    models.BooleanField(
                        default=False, verbose_name="Transfer stop"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stops",
                        to="geography.place",
                        verbose_name="Location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusStopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transit_time",
                    models.TimeField(verbose_name="Time of transit"),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shift.busstop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arrival_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_arrivals",
                        to="shift.busstoptime",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_buses",
                        to="fleet.bus",
                        verbose_name="Bus",
                    ),
                ),
                (
                    "bus_stops",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shift_stops",
                        to="shift.BusStop",
                    ),
                ),
                (
                    "departure_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_departures",
                        to="shift.busstoptime",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_drivers",
                        to="fleet.driver",
                        verbose_name="Driver",
                    ),
                ),
            ],
        ),
    ]
