# Generated by Django 3.2.5 on 2024-06-14 07:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        ("fleet", "0002_auto_20211109_1456"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_stop", models.DateTimeField(blank=True, null=True)),
                ("last_stop", models.DateTimeField(blank=True, null=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.bus"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="fleet.driver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Name of the bus stop"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geography.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arrival", models.DateTimeField()),
                (
                    "bus_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shift.busshift"
                    ),
                ),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shift.busstop"
                    ),
                ),
            ],
        ),
    ]
