# Generated by Django 3.2.5 on 2021-10-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busshift',
            name='arrival_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_stop', to='shift.busstop'),
        ),
        migrations.AddField(
            model_name='busshift',
            name='departure_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departure_stop', to='shift.busstop'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
