# Generated by Django 3.2.5 on 2021-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='bus_stops',
            field=models.ManyToManyField(help_text='Select at least 2 bus stops', related_name='shifts_stop', to='shift.BusStop'),
        ),
    ]
