# Generated by Django 3.2.5 on 2021-10-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20211022_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='time',
        ),
        migrations.CreateModel(
            name='BusStopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.busstop')),
            ],
        ),
        migrations.AlterField(
            model_name='busshift',
            name='arrival_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_stop', to='shift.busstoptime'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='departure_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departure_stop', to='shift.busstoptime'),
        ),
    ]
