# Generated by Django 3.2.5 on 2021-10-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20211022_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstoptime',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
