# Generated by Django 3.2.5 on 2021-10-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_alter_busstoptime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstoptime',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
