# Generated by Django 3.2.5 on 2021-11-08 10:13
from  datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busshifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='time',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
