# Generated by Django 3.2.5 on 2021-11-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busshifts', '0002_busstop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='stops',
        ),
        migrations.AddField(
            model_name='busstop',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='busshifts.busshift'),
            preserve_default=False,
        ),
    ]
