# Generated by Django 3.2.5 on 2022-10-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_shift', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_shift', to='fleet.driver')),
            ],
        ),
    ]
