# Generated by Django 3.2.5 on 2022-09-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Bus Stop')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geography.place')),
            ],
        ),
    ]
