# Generated by Django 3.2.5 on 2024-06-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='0')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the place')),
                ('place', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop', to='geography.place')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusLineStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default='0')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.busline')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.busstop')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('line', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='busline',
            name='stops',
            field=models.ManyToManyField(through='geography.BusLineStop', to='geography.BusStop'),
        ),
    ]
