# Generated by Django 3.2.5 on 2022-10-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
        ('geography', '0002_busstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='bus_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stop', to='journey.busshift', verbose_name='Bus shift linked to'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus_stop', to='geography.place'),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('pickup_time', 'bus_shift')},
        ),
    ]
