# Generated by Django 3.2.5 on 2024-09-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
        ("fleet", "0002_auto_20211109_1456"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        related_query_name="shift",
                        to="fleet.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        related_query_name="shift",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus shift",
                "verbose_name_plural": "Bus shifts",
            },
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Name of the bus stop"
                    ),
                ),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bus_stop",
                        to="geography.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus stop",
                "verbose_name_plural": "Bus stops",
            },
        ),
        migrations.CreateModel(
            name="BusShiftScheduledStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.TimeField(verbose_name="Time of passage through the stop"),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_stops",
                        related_query_name="scheduled_stop",
                        to="fleet.busshift",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fleet.busstop"
                    ),
                ),
            ],
            options={
                "ordering": ("time",),
            },
        ),
        migrations.AddField(
            model_name="busshift",
            name="stops",
            field=models.ManyToManyField(
                related_name="shifts",
                related_query_name="shift",
                through="fleet.BusShiftScheduledStop",
                to="fleet.BusStop",
            ),
        ),
        migrations.AddConstraint(
            model_name="busshiftscheduledstop",
            constraint=models.UniqueConstraint(
                fields=("stop", "shift"), name="unique_for_stop_shift"
            ),
        ),
        migrations.AddConstraint(
            model_name="busshiftscheduledstop",
            constraint=models.UniqueConstraint(
                fields=("shift", "time"), name="unique_for_shift_time"
            ),
        ),
    ]
