# Generated by Django 3.2.5 on 2023-06-11 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('fleet', '0003_busstop'), ('fleet', '0004_rename_stop_time_busstop_datetime'), ('fleet', '0005_busshift'), ('fleet', '0006_auto_20230610_1457'), ('fleet', '0007_alter_busstop_shift'), ('fleet', '0008_auto_20230610_1509'), ('fleet', '0009_alter_busstop_shift'), ('fleet', '0010_alter_busstop_datetime'), ('fleet', '0011_busshift_total_duration'), ('fleet', '0012_alter_busshift_total_duration'), ('fleet', '0013_alter_busstop_shift'), ('fleet', '0014_busshift_has_enough_stops'), ('fleet', '0015_alter_busstop_place'), ('fleet', '0016_auto_20230611_1507'), ('fleet', '0017_alter_busshift_total_duration'), ('fleet', '0018_alter_busshift_has_enough_stops')]

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Shift start datetime')),
                ('end_datetime', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Shift end datetime')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
                ('total_duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Total shift duration')),
                ('has_enough_stops', models.BooleanField(default=False, verbose_name='Has enough stops to be valid')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Bus stop datetime')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='geography.place')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fleet.busshift')),
            ],
        ),
    ]
