# Generated by Django 3.2.5 on 2022-06-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_time', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='geography.place')),
            ],
            options={
                'ordering': ['-pass_time'],
            },
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fleet.busstop', verbose_name='Arrival')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_shifts', to='fleet.bus', verbose_name='bus')),
                ('bus_stops', models.ManyToManyField(blank=True, related_name='bus_shifts', to='fleet.BusStop', verbose_name='Bus Stops')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fleet.busstop', verbose_name='Departure')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_shifts', to='fleet.driver', verbose_name='Drivers')),
            ],
            options={
                'verbose_name': 'Bus Shift',
                'verbose_name_plural': 'Buses Shifts',
                'unique_together': {('departure', 'arrival', 'bus', 'driver')},
            },
        ),
    ]
