# Generated by Django 3.2.5 on 2023-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_time', models.DateTimeField(verbose_name='Bus stop datetime')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='geography.place')),
            ],
        ),
    ]
