# Generated by Django 3.2.5 on 2022-09-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_busstop'),
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Shift start time')),
                ('end_time', models.DateTimeField(help_text='Shift end time')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='buses', to='fleet.bus')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drivers', to='fleet.driver')),
                ('starting_stop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='starting_stop', to='geography.busstop')),
                ('stops', models.ManyToManyField(to='geography.BusStop')),
            ],
        ),
    ]
