# Generated by Django 3.2.5 on 2021-08-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='licence_place',
            new_name='licence_plate',
        ),
    ]
