# Generated by Django 3.2.5 on 2023-02-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busstop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'ordering': ['departure_time']},
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
                ('stops', models.ManyToManyField(related_name='shifts', to='fleet.BusStop')),
            ],
        ),
    ]
