# Generated by Django 3.2.5 on 2024-11-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20241112_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='stops',
        ),
        migrations.AddField(
            model_name='busshift',
            name='bus_stop_ids',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.DeleteModel(
            name='BusShiftStop',
        ),
    ]
