# Generated by Django 3.2.5 on 2023-06-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busstop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='stop_time',
            new_name='datetime',
        ),
    ]
