# Generated by Django 3.2.5 on 2023-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busshift_busstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
