# Generated by Django 3.2.5 on 2022-12-19 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_busshift_busstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
