# Generated by Django 3.2.5 on 2024-09-24 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20240924_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='busshift',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 50, 29, 384432, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busshift',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
