# Generated by Django 3.2.5 on 2023-06-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_rename_stop_time_busstop_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Shift start datetime')),
                ('end_time', models.DateTimeField(verbose_name='Shift end datetime')),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='fleet.bus')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='fleet.driver')),
            ],
        ),
    ]
