# Generated by Django 3.2.5 on 2023-06-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_busshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='shift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_shift', to='fleet.busshift'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bus stop datetime'),
        ),
    ]
