# Generated by Django 3.2.5 on 2023-06-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20230610_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_shift', to='fleet.busshift'),
        ),
    ]
