# Generated by Django 3.2.5 on 2023-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_busstop_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='datetime',
            field=models.DateTimeField(verbose_name='Bus stop datetime'),
        ),
    ]
