# Generated by Django 3.2.5 on 2023-06-10 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_alter_busstop_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='busshift',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False, verbose_name='Total shift duration'),
            preserve_default=False,
        ),
    ]
