# Generated by Django 3.2.5 on 2023-06-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_busshift_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='total_duration',
            field=models.DurationField(verbose_name='Total shift duration'),
        ),
    ]
