# Generated by Django 3.2.5 on 2023-06-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_alter_busshift_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fleet.busshift'),
        ),
    ]
