# Generated by Django 3.2.5 on 2023-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_alter_busstop_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='busshift',
            name='has_enough_stops',
            field=models.BooleanField(default=False, verbose_name='Has enough stops to be valid'),
            preserve_default=False,
        ),
    ]
