# Generated by Django 3.2.5 on 2023-06-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0014_busshift_has_enough_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='geography.place'),
        ),
    ]
