# Generated by Django 3.2.5 on 2023-06-11 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_alter_busstop_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Shift end datetime'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Shift start datetime'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='total_duration',
            field=models.DurationField(default=0, verbose_name='Total shift duration'),
        ),
    ]
