# Generated by Django 3.2.5 on 2023-06-11 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_auto_20230611_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total shift duration'),
        ),
    ]
