# Generated by Django 3.2.5 on 2023-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_alter_busshift_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='has_enough_stops',
            field=models.BooleanField(default=False, verbose_name='Has enough stops to be valid'),
        ),
    ]
