# Generated by Django 3.2.5 on 2024-11-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stop_time', models.DateTimeField(verbose_name='Stop Time')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='geography.place')),
            ],
            options={
                'ordering': ['stop_time'],
            },
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, editable=False, null=True, verbose_name='Duration')),
                ('start_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='End Time')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.driver')),
                ('stops', models.ManyToManyField(to='trips.BusStop')),
            ],
        ),
        migrations.AddConstraint(
            model_name='busstop',
            constraint=models.UniqueConstraint(fields=('name', 'place', 'stop_time'), name='unique_place_stop_time'),
        ),
    ]
