# Generated by Django 3.2.5 on 2024-11-08 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Departure time')),
                ('end_time', models.TimeField(verbose_name='Arrival time')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.bus')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Stop name')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusShiftStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busplanning.busshift')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busplanning.busstop')),
            ],
            options={
                'db_table': 'bus_shift_stops',
                'unique_together': {('shift', 'index'), ('shift', 'stop')},
            },
        ),
        migrations.AddConstraint(
            model_name='busshift',
            constraint=models.CheckConstraint(check=models.Q(('driver', django.db.models.expressions.F('driver')), ('start_time__gte', django.db.models.expressions.F('start_time')), ('start_time__lte', django.db.models.expressions.F('start_time')), ('driver', django.db.models.expressions.F('driver')), ('end_time__gte', django.db.models.expressions.F('start_time')), ('end_time__lte', django.db.models.expressions.F('start_time'))), name='driver_planning_constraint'),
        ),
        migrations.AddConstraint(
            model_name='busshift',
            constraint=models.CheckConstraint(check=models.Q(('bus', django.db.models.expressions.F('bus')), ('start_time__gte', django.db.models.expressions.F('start_time')), ('start_time__lte', django.db.models.expressions.F('start_time')), ('bus', django.db.models.expressions.F('bus')), ('end_time__gte', django.db.models.expressions.F('start_time')), ('end_time__lte', django.db.models.expressions.F('start_time'))), name='bus_planning_constraint'),
        ),
    ]
