# Generated by Django 3.2.5 on 2024-11-08 13:56

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('busplanning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='busshift',
            name='driver_planning_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='busshift',
            name='bus_planning_constraint',
        ),
        migrations.AddConstraint(
            model_name='busshift',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lte', django.db.models.expressions.F('end_time'))), name='start_before_end_constraint'),
        ),
    ]
