# Generated by Django 3.2.5 on 2024-11-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busplanning', '0002_auto_20241108_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusShiftStops',
            new_name='BusShiftStop',
        ),
        migrations.AlterModelTable(
            name='busshiftstop',
            table='bus_shift_stop',
        ),
    ]
