# Generated by Django 3.2.5 on 2022-09-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_auto_20211109_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the bus stop')),
                ('stop_datetime', models.DateTimeField(verbose_name='Stop time')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_stop', models.DateTimeField(default=None, null=True)),
                ('last_stop', models.DateTimeField(default=None, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.bus')),
                ('bus_stops', models.ManyToManyField(to='itinerary.BusStop')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.driver')),
            ],
        ),
    ]
